

export interface Product {
    id: number;
    name: string;
    category: string;
    maker: string;
    model: string;
    year: string;
    price: number;
    salePrice: number;
    image: string;
    description: string;
    reviews: number;
    rating: number;
    discount: number;
    favorite: boolean;
}

export const productData: Product[] = [
    {
        id: 1,
        name: "Bumper (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product1.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 68,
        rating: 4,
        discount: 18,
        favorite: false,
    },
    {
        id: 2,
        name: "Doors (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product1.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 88,
        rating: 4.5,
        discount: 18,
        favorite: false,
    },
    {
        id: 3,
        name: "Fender (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product2.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 98,
        rating: 4.5,
        discount: 18,
        favorite: false,
    },
    // Duplicated for pagination demonstration
    {
        id: 4,
        name: "Bumper (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product1.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 68,
        rating: 4,
        discount: 18,
        favorite: false,
    },
    {
        id: 5,
        name: "Doors (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product3.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 88,
        rating: 4.5,
        discount: 18,
        favorite: false,
    },
    {
        id: 6,
        name: "Fender (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product3.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 98,
        rating: 4.5,
        discount: 18,
        favorite: false,
    },
    {
        id: 7,
        name: "Doors (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product2.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 88,
        rating: 4.5,
        discount: 18,
        favorite: false,
    },
    {
        id: 8,
        name: "Bumper (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product2.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 68,
        rating: 4,
        discount: 18,
        favorite: false,
    },
    {
        id: 9,
        name: "Fender (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product1.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 98,
        rating: 4.5,
        discount: 18,
        favorite: false,
    },
    {
        id: 10,
        name: "Fender (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product1.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 98,
        rating: 4.5,
        discount: 18,
        favorite: false,
    },
    {
        id: 11,
        name: "Fender (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product1.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 98,
        rating: 4.5,
        discount: 18,
        favorite: false,
    },
    {
        id: 12,
        name: "Fender (Toyota Highlander 2017)",
        category: "BODY PARTS",
        maker: "Toyota",
        model: "Highlander",
        year: "2017",
        price: 480000,
        salePrice: 460000,
        image: "/product1.png",
        description: "Designed for ultimate comfort and durability, featuring an adjustable, ergonomic fit and advanced ventilation system, with spacious compartments and easy access, it’s ideal for snowy, summer and all seasons",
        reviews: 98,
        rating: 4.5,
        discount: 18,
        favorite: false,
    },
];